# Generated by Django 4.2.2 on 2023-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('x_score', models.CharField(max_length=1)),
                ('y_score', models.CharField(max_length=1)),
            ],
        ),
    ]
