# Generated by Django 4.2.4 on 2023-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_id_alter_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
