# Generated by Django 4.2.4 on 2023-08-29 17:01

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('x', 'x'), ('y', 'y')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.JSONField(default=game.models.Game.init_status, verbose_name='status'),
        ),
    ]
