# Generated by Django 4.2.4 on 2023-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='x_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='y_score',
            field=models.IntegerField(),
        ),
    ]
